services:
  - type: web
    name: rag3-backend
    env: python
    buildCommand: "pip install -r codematrix_backend/requirements.txt"
    startCommand: "cd codematrix_backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY_1 
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
